describe("country", function()
  local t, country
  setup(function()
    t = require "t"
    country = t.country
  end)
  it("full lookup", function()
    assert.equal('US', country('UNITED STATES').id)
    assert.equal('US', country('UNITED States').id)
    assert.equal('US', country('United States').id)
    assert.equal('US', country('united states').id)
    assert.equal('US', country('united States').id)
    assert.equal('US', country('United states').id)

    assert.equal('US', country['UNITED STATES'].id)
    assert.equal('US', country['UNITED States'].id)
    assert.equal('US', country['United States'].id)
    assert.equal('US', country['united states'].id)
    assert.equal('US', country['united States'].id)
    assert.equal('US', country['United states'].id)

    assert.equal('RU', country('RUSSIA').id)
  end)
  it("id lookup", function()
    assert.equal('US', country('US').id)
    assert.equal('US', country('us').id)
    assert.equal('US', country('Us').id)
    assert.equal('US', country('uS').id)

    assert.equal('US', country['US'].id)
    assert.equal('US', country['us'].id)
    assert.equal('US', country['Us'].id)
    assert.equal('US', country['uS'].id)

    assert.equal('US', country.US.id)
    assert.equal('US', country.us.id)
    assert.equal('US', country.Us.id)
    assert.equal('US', country.uS.id)
  end)
  it("3 sym lookup", function()
    assert.equal('US', country('USA').id)
    assert.equal('US', country('usa').id)
    assert.equal('US', country('Usa').id)
    assert.equal('US', country('uSa').id)

    assert.equal('US', country['USA'].id)
    assert.equal('US', country['usa'].id)
    assert.equal('US', country['Usa'].id)
    assert.equal('US', country['uSa'].id)

    assert.equal('US', country.USA.id)
    assert.equal('US', country.usa.id)
    assert.equal('US', country.Usa.id)
    assert.equal('US', country.uSa.id)
  end)
  it("other fields", function()
    assert.equal('USA', country('US').c3)
    assert.equal('USA', country.US.c3)
    assert.equal('United States', country['US'].name)
  end)
  it("nil lookup", function()
    assert.is_nil(country())
    assert.is_nil(country(nil))
    assert.is_nil(country(''))
  end)
  it("tostring", function() assert.equal('US', tostring(country('US'))) end)
  --[[
  it("ip lookup geodb", function()
    assert.truthy(m)
    assert.truthy(m.country)
    assert.equal('US', m.country:query_by_addr('8.8.8.8').code)
  end)
--]]
  --[[
  it("ip lookup country", function()
    assert.equal('US', country('8.8.8.8').id)
    assert.equal('US', tostring(country('8.8.8.8')))
    assert.equal('RU', tostring(country('91.232.134.83')))
  end)
  it("ip lookup host", function()
    assert.equal('CH', country('46.175.8.47').id)
    assert.equal('CH', country('lua.org').id)
  end)
--]]
end)
