name: test
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  repo: ${{ github.repository }}
  ROCKSPEC: ${{ github.event.repository.name }}-scm-0.rockspec
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        luaVersion:
          - 5.1
          - 5.2
          - 5.3
          - jit
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            LUA_VERSION=${{ matrix.luaVersion }}
          load: true
          tags: ${{ github.repository }}:${{ matrix.luaVersion }}
      - name: test
        run: docker run --rm ${{ github.repository }}:${{ matrix.luaVersion }} busted-${{ matrix.luaVersion }}
