name: test
on:
  push:
    branches:
      - main
    paths:
      - '**.lua'
      - '**.t'
      - '**.yml'
      - '**.rockspec'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1", "5.2", "5.3", "luajit", "luajit-openresty"]
    env:
      DEV: --dev
      SYSDEPS: libmaxminddb-dev libmaxminddb0 build-essential make cmake git curl libssl-dev ssl-cert
      ROCKSPEC: ${{ github.event.repository.name }}-scm-0.rockspec
      LIBMAXMINDDB_INCDIR: /usr/include/x86_64-linux-gnu
    steps:
    - uses: actions/checkout@master
    - name: system dependencies
      run: sudo apt-get update -y && sudo apt-get upgrade -y ${{ env.SYSDEPS }}
    - uses: jkl1337/gh-actions-lua@v11
      with:
        luaVersion: ${{ matrix.luaVersion }}
    - uses: jkl1337/gh-actions-luarocks@v5
    - name: test deps
      run: luarocks install lua-maxminddb LIBMAXMINDDB_DIR=/usr/include/x86_64-linux-gnu
    - name: test deps
      run: luarocks test --prepare ${{ env.DEV }}
    - name: dependencies
      run: luarocks install --deps-mode all --only-deps ${{ env.DEV }} ${{ env.ROCKSPEC }}
    - name: build
      run: luarocks build --deps-mode all ${{ env.DEV }} ${{ env.ROCKSPEC }}
    - name: test
      run: luarocks test -- -o TAP
