name: test
on:
  push:
    branches:
      - main
    paths:
      - '**.lua'
      - '**.mmdb'
      - '**.mk'
      - '**.yml'
      - '**.rockspec'
  workflow_dispatch:
env:
  IMAGE: ${{ github.repository }}
  ROCKSPEC: ${{ github.event.repository.name }}-scm-0.rockspec
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["5.1", "5.2", "5.3", "jit"]
    env:
      version: ${{ matrix.version }}
      tag: ${{ github.repository }}:${{ env.version }}
      busted: busted-${{ env.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.tag }}
      - name: test
        run:  docker run --rm ${{ env.tag }} ${{ env.busted }}
